# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88033cb919b98189382b8cc68b28d7637a7aabab2735f44ecafade19ca67c23ae88b76d1304ff53b0d6fb1dd395fec3cd3ff93c591db51698e4185e14e9e5c1

test:
  secret_key_base: a77126e43882c4d52c225a2a0ffe0aab971f0a1dbde469b5bf11a34d55af2990c520d61acaab525e45ac5389628932cc6ff8bc8fbaef5fd351ff11922314c2fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
